addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"   % "0.13.0")
addSbtPlugin("com.github.sbt" % "sbt-pgp"         % "2.3.1")
addSbtPlugin("com.github.sbt" % "sbt-release"     % "1.4.0")
addSbtPlugin("org.jetbrains"  % "sbt-idea-plugin" % "3.26.2")
addSbtPlugin("org.scala-js"   % "sbt-scalajs"     % "1.17.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"    % "3.12.2")
