addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"            % "0.12.0")
addSbtPlugin("com.github.sbt"     % "sbt-pgp"                  % "2.2.1")
addSbtPlugin("com.github.sbt"     % "sbt-release"              % "1.4.0")
addSbtPlugin("org.jetbrains"      % "sbt-idea-plugin"          % "3.26.2")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.16.0")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"             % "3.10.0")
