addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"   % "0.13.1")
addSbtPlugin("com.github.sbt" % "sbt-pgp"         % "2.3.1")
addSbtPlugin("com.github.sbt" % "sbt-release"     % "1.4.0")
addSbtPlugin("org.jetbrains"  % "sbt-idea-plugin" % "4.1.5")
addSbtPlugin("org.scala-js"   % "sbt-scalajs"     % "1.19.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"    % "3.12.2")
